ALTER TABLE "disciplinas"
  ADD COLUMN "tipo" "TipoComponente" NOT NULL DEFAULT 'ESPECIFICO',
  ADD COLUMN "tipoEntrega" "TipoEntrega" NOT NULL DEFAULT 'PRESENCIAL_FISICO',
  ADD COLUMN "chTotal" INTEGER NOT NULL DEFAULT 60,
  ADD COLUMN "chPresencial" INTEGER NOT NULL DEFAULT 60,
  ADD COLUMN "chSincrona" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN "chAssincrona" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN "chExtensao" INTEGER NOT NULL DEFAULT 0;
